import Head from "next/head";
import Header from "../components/Header";
import HomePage from "../components/HomePage";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="font-sans text-gray-400">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen p-6 lg:px-20 flex flex-col gap-y-8 bg-slate-900">
        <Header />
        <HomePage />
      </div>
      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
