import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import HomePage from "../components/HomePage";
import InfoPage from "../components/InfoPage";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="font-sans text-gray-400">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen p-6 lg:px-20 flex flex-col gap-y-8 bg-slate-900">
        <Header />
        <HomePage />
      </div>
      <div className="p-6 lg:px-20 flex flex-col gap-y-8 bg-slate-800">
        <InfoPage />
        <div className="bg-gray-600 h-px w-full"></div>
        <Footer />
      </div>
    </div>
  );
}
